'use strict';var _totpGenerator=require('totp-generator');var _totpGenerator2=_interopRequireDefault(_totpGenerator);function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj};}var url=new URL(window.location.href);console.log(url);var kinput=url.searchParams.get('k');if(kinput==undefined){document.getElementById('instructions').hidden=false;throw new Error('Key is not specified!');}kinput=kinput.trim();if(kinput.slice(-1)==';')kinput=kinput.slice(0,-1);console.log(kinput);var setTime=url.searchParams.get('t')||undefined;console.log('setTime',setTime);var keydict=kinput.split(';');var success=false;try{for(var key in keydict){keydict[key]=keydict[key].trim();var k=keydict[key].split(',');var optstrs=k.slice(2);var optdict={};for(var entry in optstrs){var pair=optstrs[entry].split(':');optdict[pair[0]]=pair[1];}console.log(optdict);var dict={n:k[0].trim(),// name
k:k[1].trim(),// keystring
o:k.slice(2),// option string
options:optdict// parsed options
};keydict[key]=dict;}success=true;}finally{if(success==false){document.write('Format Error! Input string cannot be parsed!');throw new Error('Format Error!');}}console.log(keydict);// function to calculate
function calc(keydict){var res={};for(var each in keydict){var name=keydict[each].n;var op=keydict[each].options;var tokn=(0,_totpGenerator2.default)(keydict[each].k,{digits:op['d']||6,algorithm:op['a']||"SHA-1",period:op['p']||30,timestamp:setTime||Date.now()});res[name]=tokn;}return res;}// create the list displays
var insertpos=document.getElementById('displays');for(var item in keydict){var name=keydict[item].n;var elm=document.createElement('div');var infotext=keydict[item].o;elm.innerHTML='\n    <h2 id="title-'+name+'">'+name+'</h2>\n    <h2 id="code-'+name+'"></h2>\n    <p>Next Refresh: <span id="remainSec-'+name+'">N/A</span></p>\n    <pre>'+infotext+'</pre>\n    <hr>\n    ';insertpos.appendChild(elm);}// refresh passwords
function refresh(){var timeNow=Math.floor(Date.now()/1000);var timeIsFixed='';if(setTime){timeNow=setTime;timeIsFixed='FREEZED';}document.getElementById('Time').innerText='Current Timestamp: '+timeNow+' '+timeIsFixed;var results=calc(keydict);for(var _item in keydict){// update code
var _elm=document.getElementById('code-'+keydict[_item].n);_elm.innerText=results[keydict[_item].n];// update time counter
if(setTime==undefined){var remainTimeDisp=document.getElementById('remainSec-'+keydict[_item].n);var thisPeriod=keydict[_item].options.p||30;remainTimeDisp.innerText=thisPeriod-timeNow%thisPeriod;}}console.log('Code Updated.',timeNow);if(setTime==undefined)setTimeout(refresh,1000);}var refreshSuccess=false;try{refresh();refreshSuccess=true;}finally{if(refreshSuccess==false){document.write("Incorrect format or invalid parameters!");throw new Error("Cannot refresh, format or value error");}}